version: '3.3'
networks:
  traefik-local:
    external: true
services:
  app:
    container_name: go
    build: .
    volumes:
      - ./code:/go/src/app
    environment:
      PORT: 3001
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.basic.port=3000"
      - "traefik.basic.protocol=http"
      - "traefik.backend=golang"
      - "traefik.frontend.rule=Host:golang.localhost"
      - "traefik.docker.network=traefik-local"
    networks:
      - traefik-local
